import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import "./globals.css";

import Providers from "@/components/Providers";
import authOptions from "@/utils/authOptions";
import SessionProvider from "/components/SessionProvider";
import { Toaster } from "react-hot-toast";
import LaunchModal from "@/components/launch/LaunchModal";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="box-border">
      <body className="bg-[#0D0701] px-4 md:container mx-auto mt-8 font-gafata">
        <SessionProvider session={session}>
          <Providers>
            <Toaster />
            <Navbar />
            <LaunchModal />
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
